=== anabelgv/Validation_computer_shop_XML/ComputerShop.dtd
<!ELEMENT Computer_Shop (products,customers,sales)>
<!-- Products-->
<!ELEMENT products (product*)>
<!ELEMENT product (title,(manufactured|brand),model,price,stock,reconditioned?)>
<!ATTLIST product id ID #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT brand (#PCDATA)> <!-- manufacturer and brand-->
<!ELEMENT model (#PCDATA)>
<!ELEMENT manufactured EMPTY>

<!ELEMENT price EMPTY>
<!ATTLIST price currency (EUR|USD) #REQUIRED>
<!ATTLIST price price_discount CDATA "0">

<!ELEMENT stock EMPTY>
<!ATTLIST stock vat (general|reduced|super-reduced) "">
<!ATTLIST stock ean CDATA #IMPLIED>
<!ELEMENT reconditioned EMPTY>
<!-- Customers-->
<!ELEMENT customers (customer*)>
<!ELEMENT customer (id_card,((first_name,surnames)|complete_name),telephone_number*,postal_address)>
<!ATTLIST customer id ID #REQUIRED>                             <!-- varios o ninguno-->


<!ELEMENT id_card (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT surnames (#PCDATA)>
<!ELEMENT telephone_number (#PCDATA)>

<!ELEMENT postal_address (#PCDATA)>
<!ATTLIST postal_address date_creation CDATA #REQUIRED>
<!-- Sales-->
<!ELEMENT sales (sale)>
<!ELEMENT sale (list_products_sold,total_price,currency)>
<!ATTLIST sale date CDATA #REQUIRED>
<!ATTLIST sale customer IDREF #REQUIRED>
<!ATTLIST sale product_id IDREF #REQUIRED>

<!ELEMENT list_products_sold (item+)>
<!ELEMENT item (#PCDATA)>
<!ATTLIST list_products_sold Quantity NMTOKEN "1">

<!ELEMENT total_price (#PCDATA)>
<!ELEMENT currency (#PCDATA)>

=== anabelgv/Validation_computer_shop_XML/ComputerShop.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Computer_Shop SYSTEM "ComputerShop.dtd">
<Computer_Shop>
    <products> 
        <product id="P1">
            <title></title>
            <brand></brand>
            <model></model>
            <price currency="EUR" price_discount="0"></price>
            <stock vat="reduced" ean=""></stock>
            <reconditioned></reconditioned>

        </product>
        <product id="P2">
            <title></title>
            <brand></brand>
            <model></model>
            <price currency="USD" price_discount="0"></price>
            <stock vat="general" ean=""></stock><!-- reconditioned-->

        </product>
    </products>
    <customers>
        <customer id="C1">
            <id_card></id_card>
            <first_name></first_name>
            <surnames></surnames>
            <telephone_number></telephone_number>
            <postal_address date_creation=""></postal_address>
        </customer>
    </customers>
    <sales>
        <sale date="01/06/2020" customer="C1" product_id="P2">
            <list_products_sold Quantity="2">
                <item>orange</item>
            </list_products_sold>
            <total_price></total_price>
            <currency></currency>
        </sale>

    </sales>


</Computer_Shop>
